issue_form_config:
  templates:
    Bug Report: .github/ISSUE_TEMPLATE/bug_report.md
    Feature Request: .github/ISSUE_TEMPLATE/feature_request.md
pull_request_template: .github/PULL_REQUEST_TEMPLATE/pull_request_template.md